# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - dev

schedules:
  - cron: "30 11 * * Wed,Fri" # Runs at 5:00 PM IST (11:30 AM UTC)
    displayName: "Scheduled Build - Wednesday and Friday at 5 PM IST"
    branches:
      include:
        - dev
    always: true # Ensures the pipeline runs even if there are no code changes

pool:
  name: "Default"
  vmImage: ubuntu-latest

variables:
  # JAVA_HOME_11_X64: "/usr/lib/jvm/java-11-openjdk"
  JAVA_HOME_11_X64: "C:/Program Files/Java/jdk-11"

# Builds the maven project using jdk 11
steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "pom.xml"
      goals: "clean package"
      mavenOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      continueOnError: true

  # Creates workitem (Bug) on build failure
  - task: CreateWorkItem@2
    condition: failed()
    inputs:
      workItemType: "Bug"
      title: "Bug created on build fail"
      associate: true
      associationType: build
      assignedTo: "$(ASSIGNEE_EMAIL)"
      authType: "pat"
      authToken: "$(PAT_TOKEN)"

  # Publish and runs JUnit Tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      testRunTitle: "JUnit Test Results"

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/target/reports/surefire-reports/TEST-*.xml"
      pathToSources: "$(System.DefaultWorkingDirectory)/src/main/java"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/target"
      Contents: "**/*.war"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  # On successfull build artifacts are published
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      goals: "package"
