name: Maven Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4

      - name: Set up the Java environment (JDK) for Maven builds
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project using Maven
        run: mvn install -B

      - name: Run tests using Maven
        run: mvn test
