name: CI/CD Pipeline - Spring MVC Calculator

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev
      - 'feature/**'
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * 3' # Every Wednesday at 11:30 UTC
    - cron: '30 11 * * 5' # Every Friday at 11:30 UTC

jobs:
  build-test-analyze:
    name: Build, Test, Quality Analysis, and Artifact Management
    runs-on: self-hosted

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Set up latest Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 'latest'

      - name: Display Java and Maven versions
        run: |
          java -version
          mvn -version

      - name: Build with Maven (includes tests)
        run: mvn -B package --file pom.xml

      - name: Run JUnit tests
        run: mvn test

      - name: Generate Surefire Test Reports
        run: mvn surefire-report:report

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Upload Build Artifacts (.jar/.war)
        uses: actions/upload-artifact@v4
        with:
          name: spring-mvc-app-${{ github.ref_name }}-${{ github.sha }}
          path: |
            target/**/*.jar
            target/**/*.war
          retention-days: 14

      - name: Upload Surefire Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.ref_name }}-${{ github.sha }}
          path: target/site/surefire-report.html
          retention-days: 14

      - name: Upload JaCoCo Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.ref_name }}-${{ github.sha }}
          path: |
            target/site/jacoco/index.html
            target/site/jacoco/*
          retention-days: 14
