name: CI/CD Pipeline - Java Maven Spring MVC

on:
  push:
    branches:
      - nexops-pipeline_20250808_102709
  pull_request:
    branches:
      - master
      - nexops-pipeline_20250808_102709
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven local repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and build
        run: mvn -B clean package
        env:
          MAVEN_OPTS: -Dmaven.test.skip=false

      - name: Run JUnit tests
        run: mvn -B test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-artifacts
          path: target/
